In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [34]:
df=pd.read_csv(r"C:\AI_Learning\Week5\Day1\Admission_Predict.csv")

In [35]:
df.shape

(400, 9)

In [36]:
df.sample(5)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
174,175,321,111,4,4.0,4.0,8.97,1,0.87
312,313,311,107,4,4.5,4.5,9.00,1,0.78
362,363,338,115,5,4.5,5.0,9.23,1,0.91
224,225,305,105,2,3.0,2.0,8.23,0,0.67
341,342,326,110,3,3.5,3.5,8.76,1,0.79

In [37]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [38]:
df.drop("Serial No.", axis=1, inplace=True)

In [39]:
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65

In [40]:
x=df.iloc[:,0:-1].values
y=df.iloc[:,-1].values

In [41]:
x

array([[337.  , 118.  ,   4.  , ...,   4.5 ,   9.65,   1.  ],
       [324.  , 107.  ,   4.  , ...,   4.5 ,   8.87,   1.  ],
       [316.  , 104.  ,   3.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [330.  , 116.  ,   4.  , ...,   4.5 ,   9.45,   1.  ],
       [312.  , 103.  ,   3.  , ...,   4.  ,   8.78,   0.  ],
       [333.  , 117.  ,   4.  , ...,   4.  ,   9.66,   1.  ]],
      shape=(400, 7))

In [42]:
from sklearn.preprocessing import StandardScaler
x_scaler=StandardScaler()

In [43]:
x=x_scaler.fit_transform(x)
y=y.reshape(-1, 1)

In [44]:
x

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, ...,  0.05293342,
        -1.00563118,  0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.16732114,
         1.42900622,  0.90911166],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.61012728,
         0.30403584, -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  0.61012728,
         1.78160888,  0.90911166]], shape=(400, 7))

In [45]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.1, random_state=0)

In [46]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [47]:
model=Sequential()

In [48]:
xtrain.shape

(360, 7)

In [49]:
model.add(Dense(3,activation="relu", input_dim=xtrain.shape[1]))
model.add(Dense(1,activation="linear"))

c:\Users\PranitaBhatt\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [50]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 3)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 28 (112.00 B)

 Trainable params: 28 (112.00 B)

 Non-trainable params: 0 (0.00 B)

In [51]:
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

In [52]:
model.fit(xtrain, ytrain, epochs=50, batch_size=10,verbose=1)

Epoch 1/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2749 - mae: 0.4584
Epoch 2/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2275 - mae: 0.4114
Epoch 3/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1949 - mae: 0.3763
Epoch 4/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1689 - mae: 0.3474
Epoch 5/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1478 - mae: 0.3235
Epoch 6/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1298 - mae: 0.3027
Epoch 7/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1144 - mae: 0.2839
Epoch 8/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1004 - mae: 0.2660
Epoch 9/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0882 - mae: 0.2486
Epoch 10/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0773 - mae: 0.2323
Epoch 11/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0677 - mae: 0.2168
Epoch 12/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0592 - mae: 0.2022
Epoch 13/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0520 - mae: 0.1886
Epoch 14/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0460 - mae: 0.1759
Epoch 15/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0412 - mae: 0.1649
Epoch 16/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0370 - mae: 0.1553
Epoch 17/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0337 - mae: 0.1474
Epoch 18/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0309 - mae: 0.1400
Epoch 19/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0286 - mae: 0.1339
Epoch 20/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0266 - mae: 0.1284
Epoch 21/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0249 - mae: 0.1244
Epoch 22/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0233 - mae: 0.1198
Epoch 23/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0219 - mae: 0.1159
Epoch 24/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0208 - mae: 0.1129
Epoch 25/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0196 - mae: 0.1093
Epoch 26/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0187 - mae: 0.1068
Epoch 27/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0178 - mae: 0.1039
Epoch 28/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0169 - mae: 0.1009
Epoch 29/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0161 - mae: 0.0983
Epoch 30/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0153 - mae: 0.0957
Epoch 31/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0146 - mae: 0.0932
Epoch 32/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0139 - mae: 0.0910
Epoch 33/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0134 - mae: 0.0893
Epoch 34/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0128 - mae: 0.0871
Epoch 35/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0123 - mae: 0.0855
Epoch 36/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0119 - mae: 0.0842
Epoch 37/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0115 - mae: 0.0829
Epoch 38/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0112 - mae: 0.0815
Epoch 39/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0108 - mae: 0.0803
Epoch 40/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0105 - mae: 0.0791
Epoch 41/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0102 - mae: 0.0780
Epoch 42/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0099 - mae: 0.0766
Epoch 43/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0096 - mae: 0.0756
Epoch 44/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0094 - mae: 0.0746
Epoch 45/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0091 - mae: 0.0738
Epoch 46/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0089 - mae: 0.0727
Epoch 47/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0087 - mae: 0.0718
Epoch 48/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0085 - mae: 0.0709
Epoch 49/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0082 - mae: 0.0700
Epoch 50/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0081 - mae: 0.0693

In [53]:
ypred=model.predict(xtest).ravel()
ytest_actual=ytest.ravel()

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

In [54]:
from sklearn.metrics import r2_score
r2_score(ytest_actual, ypred)

0.6168122628508308